//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeGen {
    
    public partial class BarcodeReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "BarcodeGen.BarcodeReport.vsrepx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.bottomMarginBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("bottomMarginBand1");
            this.XrBarCode = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRBarCode>("XrBarCode");
            this.XrPatientDetails = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrPatientDetails");
            this.XrLabel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel1");
            this.XrLabel2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("XrLabel2");

            // Parameters
            this.BarcodeData = reportInitializer.GetParameter("BarcodeData");
            this.PatientData = reportInitializer.GetParameter("PatientData");
            this.DateTime = reportInitializer.GetParameter("DateTime");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand bottomMarginBand1;
        private DevExpress.XtraReports.UI.XRBarCode XrBarCode;
        private DevExpress.XtraReports.UI.XRLabel XrPatientDetails;
        private DevExpress.XtraReports.UI.XRLabel XrLabel1;
        private DevExpress.XtraReports.UI.XRLabel XrLabel2;
        private DevExpress.XtraReports.Parameters.Parameter BarcodeData;
        private DevExpress.XtraReports.Parameters.Parameter PatientData;
        private DevExpress.XtraReports.Parameters.Parameter DateTime;
    }
}
